line-length = 120
target-version = "py310"

[lint]
select = ["E", "F", "I", "N", "UP", "B", "C4", "SIM"]
ignore = ["E501"]
exclude = [
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "ui/*",
    "services/*",
    "scripts/*",
    "tests/*",
    "app.py",
    "audio_utils.py",
    "config.py",
    "fluent_gui.py",
    "waveform_viewer.py",
    "wav_extractor_wave.py",
    "pdf_viewer.py",
    "settings_page.py"
]

[lint.per-file-ignores]
"tests/test_characterization.py" = ["F401"]
